services:

  traefik:
    image: traefik:${TRAEFIK_VERSION:-3}
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-dashboard.rule=Host(`${FQDN_TRAEFIK:-traefik.test}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-dashboard.service=api@internal"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-dashboard.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-dashboard.tls=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
    depends_on:
      - moodle

  moodle:
    build: .
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_PASSWORD=12345Abcde
      - PHP_INI-post_max_size=16G
      - PHP_INI-upload_max_filesize=16G
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-moodle.rule=Host(`${FQDN_MOODLE:-moodle.test}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-moodle.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-moodle.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-moodle.loadbalancer.server.port=80"
    volumes:
      - moodledata:/var/www/moodledata
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:11.8
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: 12345Abcde
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  https-portal_certs:
  https-portal_logs:
  moodledata:
  mariadb:
