services:

  traefik:
    image: traefik:${TRAEFIK_VERSION:-3}
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-dashboard.rule=Host(`${FQDN_TRAEFIK:-traefik.test}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-dashboard.service=api@internal"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-dashboard.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-dashboard.tls=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
    depends_on:
      - moodle

  moodle:
    build:
      context: .
      args:
        - MOODLE_BRANCH=${MOODLE_BRANCH:-MOODLE_502_STABLE}
        - MOODLE_DATABASE_HOST=${MOODLE_DATABASE_HOST:-mariadb}
        - MOODLE_DATABASE_PORT_NUMBER=${MOODLE_DATABASE_PORT_NUMBER:-3306}
        - MOODLE_DATABASE_NAME=${MOODLE_DATABASE_NAME:-moodle}
        - MOODLE_DATABASE_USER=${MOODLE_DATABASE_USER:-moodle}
        - MOODLE_DATABASE_PASSWORD=${MOODLE_DATABASE_PASSWORD:-12345Abcde}
        - MOODLE_WWWROOT=https://${FQDN_MOODLE:-moodle.test}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-moodle.rule=Host(`${FQDN_MOODLE:-moodle.test}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-moodle.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-moodle.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-moodle.loadbalancer.server.port=80"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-moodle.loadbalancer.server.scheme=http"
    volumes:
      - moodledata:/var/www/moodledata
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:11.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      - MYSQL_DATABASE=${MOODLE_DATABASE_NAME:-moodle}
      - MYSQL_USER=${MOODLE_DATABASE_USER:-moodle}
      - MYSQL_PASSWORD=${MOODLE_DATABASE_PASSWORD:-12345Abcde}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  https-portal_certs:
  https-portal_logs:
  moodledata:
  mariadb:
